<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ApplicationStatus extends Model
{
    use HasFactory;

    const SUBMITTED = 'submitted';
    const VERIFIED = 'verified';
    const APPROVED = 'approved';
    const PLANNING_VERIFIED = 'planning-verified';
    const PLANNING_APPROVED = 'planning-approved';
    const EXECUTIVE_APPROVED = 'executive-approved';
    const GOVERNING_APPROVED = 'governing-approved';

    protected $fillable = ['name', 'application_id','user_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (ApplicationStatus $status) {
            $status->user_id = auth()->id();
        });
    }

    public function application(): BelongsTo
    {
        return $this->belongsTo(Application::class);
    }
}
